from datetime import date, datetime
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from app.models import ApprovalState, PinType, RoleEnum, SiteStatus, TMTicketStatus


class UserRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    name: str
    email: str
    role: RoleEnum


class SiteSprayRecordRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    site_id: int
    spray_date: date
    sprayed_by_user_id: int | None
    sprayed_by_name: str | None
    notes: str | None
    is_avoided: bool
    created_at: datetime
    ticket_number: str | None = None
    lease_sheet_data: dict | None = None
    pdf_url: str | None = None
    photo_urls: list[str] | None = None
    tm_ticket_id: int | None = None


class SiteSprayRecordSummary(BaseModel):
    """Lightweight spray-record view without lease_sheet_data.

    Used by list endpoints to keep egress tiny. For the full record (edit /
    deep inspection), call GET /api/site-spray-records/{id}.
    """
    model_config = ConfigDict(from_attributes=True)

    id: int
    site_id: int
    spray_date: date
    sprayed_by_user_id: int | None
    sprayed_by_name: str | None
    notes: str | None
    is_avoided: bool
    created_at: datetime
    ticket_number: str | None = None
    pdf_url: str | None = None
    photo_urls: list[str] | None = None
    tm_ticket_id: int | None = None


class TimeMaterialsLink(BaseModel):
    """Instruction for linking a lease sheet to a T&M ticket on submit."""
    ticket_id: int | None = None           # link to existing ticket
    create: bool = False                    # create new ticket from this lease sheet
    description_of_work: str | None = None  # required when create=True
    tm_pdf_base64: str | None = None        # frontend-generated T&M PDF after this row is appended


class SiteSprayRecordCreate(BaseModel):
    spray_date: date
    notes: str | None = None
    is_avoided: bool = False
    site_status: SiteStatus | None = None
    lease_sheet_data: dict | None = None
    pdf_base64: str | None = None
    ticket_number: str | None = None
    time_materials_link: TimeMaterialsLink | None = None
    # Idempotency key generated by the frontend when an offline lease sheet
    # is queued. If the upload retries after the server already committed,
    # the create endpoint returns the existing record instead of inserting
    # a duplicate (and burning a 2nd HL ticket number).
    client_submission_id: str | None = None


class SiteSprayRecordUpdate(BaseModel):
    spray_date: date | None = None
    notes: str | None = None
    is_avoided: bool | None = None
    lease_sheet_data: dict | None = None
    pdf_base64: str | None = None
    ticket_number: str | None = None
    tm_pdf_base64: str | None = None  # regenerated T&M PDF after edit propagation


class ExternalLeaseSheetCreate(BaseModel):
    """Standalone lease sheet for a location not on the map."""
    spray_date: date
    notes: str | None = None
    is_avoided: bool = False
    lease_sheet_data: dict | None = None
    pdf_base64: str | None = None
    ticket_number: str | None = None
    time_materials_link: TimeMaterialsLink | None = None
    client_submission_id: str | None = None
    latitude: float | None = None
    longitude: float | None = None


class RecentSubmissionRead(BaseModel):
    """Lightweight recent-submission row — NO lease_sheet_data.

    The PDF preview fetches the real Dropbox PDF via /api/pdf-proxy; the edit
    flow fetches the full record via /api/site-spray-records/{id}.
    """
    model_config = ConfigDict(from_attributes=True)

    id: int
    # site_id is None for pipeline-sourced lease sheets; pipeline_id is None
    # for site-sourced ones. Exactly one is set per row.
    site_id: int | None = None
    pipeline_id: int | None = None
    spray_date: date
    sprayed_by_user_id: int | None
    sprayed_by_name: str | None
    notes: str | None
    is_avoided: bool
    created_at: datetime
    ticket_number: str | None = None
    pdf_url: str | None = None
    photo_urls: list[str] | None = None
    tm_ticket_id: int | None = None
    # Joined site/pipeline context. For pipeline rows, site_lsd holds the
    # pipeline name so the existing "lsd • client • area" row renders
    # meaningfully without changing the frontend schema.
    site_lsd: str | None = None
    site_client: str | None = None
    site_area: str | None = None


class SiteUpdateRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    status: SiteStatus
    note: str | None
    sync_status: str
    created_at: datetime
    created_by_user_id: int | None


class SiteRead(BaseModel):
    """Full site view — returned ONLY by `GET /api/sites/{id}` and by the
    create/update/patch endpoints. Includes heavy fields (`updates`,
    `spray_records`, `raw_attributes`, nested user objects) that the map and
    list views don't need.

    For lists (map pins, filter panels, delta polls) use `SiteListRead` — it
    omits everything listed above, which is the single biggest egress win on
    the Supabase pooler.
    """
    model_config = ConfigDict(from_attributes=True)

    id: int
    pin_type: PinType
    lsd: str | None
    client: str | None
    area: str | None
    latitude: float
    longitude: float
    status: SiteStatus
    approval_state: ApprovalState
    gate_code: str | None
    phone_number: str | None
    notes: str | None
    source: str
    source_name: str | None
    raw_attributes: dict | None
    last_inspected_at: datetime | None
    last_inspected_by_user_id: int | None
    last_inspected_by_email: str | None
    last_inspected_by_name: str | None
    created_at: datetime
    updated_at: datetime
    created_by_user_id: int | None
    created_by_name: str | None = None
    approved_by_user_id: int | None
    pending_pin_type: PinType | None = None
    pending_change_requested_by_user_id: int | None = None
    pending_change_requested_by_name: str | None = None
    updates: list[SiteUpdateRead] = Field(default_factory=list)
    spray_records: list[SiteSprayRecordSummary] = Field(default_factory=list)
    # Nested user objects for convenience
    created_by_user: UserRead | None = None
    approved_by_user: UserRead | None = None
    last_inspected_by_user: UserRead | None = None
    pending_change_requested_by_user: UserRead | None = None

    @field_validator('raw_attributes', mode='before')
    @classmethod
    def parse_raw_attributes(cls, v):
        if isinstance(v, str):
            try:
                return json.loads(v)
            except json.JSONDecodeError:
                return None
        return v


class SiteListRead(BaseModel):
    """Slim site view — only what the map / filter panels / delta poll need.

    Dropped vs. `SiteRead`:
      - `updates`          (history shipped on every delta; frontend never reads it)
      - `spray_records`    (each site accumulates these forever; detail view
                            refetches via /api/sites/{id})
      - `raw_attributes`   (KML metadata blob, unused by the frontend)
      - `created_by_user`, `approved_by_user`, `last_inspected_by_user`
                           (nested user objects; the scalar `*_name` /
                            `*_email` columns cover every UI use-case)

    Kept: everything the map pin, marker icon, filter, and site-row rendering
    actually read — plus a cheap `has_spray_records` boolean so the UI can
    show a "📄 N spray records" badge without loading the full list.

    Net effect on /api/sites egress: ~50-70% reduction on medium datasets.
    """
    model_config = ConfigDict(from_attributes=True)

    id: int
    pin_type: PinType
    lsd: str | None
    client: str | None
    area: str | None
    latitude: float
    longitude: float
    status: SiteStatus
    approval_state: ApprovalState
    gate_code: str | None
    phone_number: str | None
    notes: str | None
    source: str
    source_name: str | None
    last_inspected_at: datetime | None
    last_inspected_by_user_id: int | None
    last_inspected_by_email: str | None
    last_inspected_by_name: str | None
    created_at: datetime
    updated_at: datetime
    created_by_user_id: int | None
    created_by_name: str | None = None
    approved_by_user_id: int | None
    pending_pin_type: PinType | None = None
    pending_change_requested_by_user_id: int | None = None
    pending_change_requested_by_name: str | None = None
    # Cheap flag so the UI can still show a "has lease sheets" badge without
    # hydrating the spray_records list. Populated by the endpoint.
    has_spray_records: bool = False


class SiteCreate(BaseModel):
    pin_type: PinType
    status: SiteStatus = SiteStatus.not_inspected
    lsd: str | None = None
    client: str | None = None
    area: str | None = None
    latitude: float
    longitude: float
    gate_code: str | None = None
    phone_number: str | None = None
    notes: str | None = None
    # Idempotency key for offline-queued pin creation. Persisted into
    # Site.raw_attributes (no dedicated column — pins don't burn a sequence
    # value so the consequence of a duplicate is just an extra row, but we
    # still dedupe to keep the Pending Pins list clean).
    client_submission_id: str | None = None


class SiteStatusUpdate(BaseModel):
    status: SiteStatus
    note: str | None = None


class SiteAdminUpdate(BaseModel):
    pin_type: PinType | None = None
    lsd: str | None = None
    client: str | None = None
    area: str | None = None
    latitude: float | None = None
    longitude: float | None = None
    gate_code: str | None = None
    phone_number: str | None = None
    notes: str | None = None


class SprayRecordApprovalUpdate(BaseModel):
    """Per-spray-record instruction emitted by the approval dialog.

    Carries the regenerated lease-sheet PDF (so Dropbox stays in sync with
    the corrected client/area/lsd) and, when the spray record currently
    lives on a shared T&M ticket and meta has changed, a `tm_link`
    directive telling the backend how to re-home this record's T&M rows
    (pick an existing ticket by id, or create a new one for the corrected
    `(client, area, spray_date)`).
    """
    spray_record_id: int
    lease_pdf_base64: str | None = None
    tm_link: TimeMaterialsLink | None = None
    tm_pdf_base64: str | None = None


class SiteApprovalUpdate(BaseModel):
    approval_state: ApprovalState
    lsd: str | None = None
    client: str | None = None
    area: str | None = None
    notes: str | None = None
    gate_code: str | None = None
    phone_number: str | None = None
    # Regenerated artifacts + re-home choices for each linked spray record.
    # Required when approval_state=approved AND any linked spray record
    # exists AND lsd/client/area is being changed. See update_site_approval.
    spray_record_updates: list[SprayRecordApprovalUpdate] | None = None
    # Regenerated T&M PDF when the linked ticket is DEDICATED (all rows on
    # it trace to the one spray record being approved). Shared-ticket
    # re-homes carry their own tm_pdf_base64 inside tm_link.
    dedicated_tm_pdf_base64: str | None = None


class SiteApprovalConflictDetail(BaseModel):
    """Structured 409 body surfaced by POST /api/sites/{id}/approval and
    POST /pipelines/{id}/approval so the frontend can show an actionable
    dialog without re-parsing error strings.
    """
    # "has_linked_spray_records" → reject blocked because lease sheets exist.
    # "shared_tm_ticket_needs_rehome" → approve blocked because a meta change
    #     would corrupt a T&M ticket shared with other spray records; admin
    #     must resubmit with tm_link choices.
    reason: str
    linked_spray_records: list[dict] = Field(default_factory=list)
    shared_ticket_conflicts: list[dict] = Field(default_factory=list)
    open_tm_tickets: list[dict] = Field(default_factory=list)


class SiteQuickEdit(BaseModel):
    gate_code: str | None = None
    phone_number: str | None = None
    notes: str | None = None


class BulkResetRequest(BaseModel):
    client: str | None = None
    area: str | None = None


class BulkResetResponse(BaseModel):
    reset_count: int


class KmlImportResponse(BaseModel):
    imported_count: int


class TypeChangeRequest(BaseModel):
    pin_type: PinType


class SessionResponse(BaseModel):
    user: UserRead


# ── Delta-sync response envelopes ──
#
# Each delta endpoint returns a small payload describing what changed since
# the caller's last-seen timestamp, rather than the entire resource list.
# The frontend uses `server_time` as the next `?since=...` value so clocks
# don't drift and nothing is ever skipped.


class SitesDeltaResponse(BaseModel):
    """Incremental sites update.

    `items` — sites created/updated (and still visible) since `since`.
    `ids_removed` — site IDs that were soft-deleted or rejected since `since`;
    frontend should drop them from its cache/map.
    `server_time` — pass this back as `?since=` on the next call.

    Uses the slim `SiteListRead` schema — heavy relations (updates,
    spray_records, raw_attributes, nested users) are NOT shipped in the delta.
    The frontend merges these items into its cache without clobbering any
    previously-loaded heavy fields; detail views refetch via /api/sites/{id}.
    """
    items: list[SiteListRead]
    ids_removed: list[int]
    server_time: datetime


class RecentSubmissionsDeltaResponse(BaseModel):
    """Incremental recent-submissions update. Includes new/updated rows
    and ids_removed for soft-deleted lease sheets so frontend caches can
    prune accordingly."""
    items: list[RecentSubmissionRead]
    ids_removed: list[int]
    server_time: datetime


# ── Time & Materials Ticket schemas ──

class TimeMaterialsRowRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    ticket_id: int
    # Exactly one of these two is non-null per the DB CHECK constraint
    # ck_tm_rows_exactly_one_spray_fk. Site-sourced rows populate
    # spray_record_id; pipeline-sourced rows populate pipeline_spray_record_id.
    spray_record_id: int | None = None
    pipeline_spray_record_id: int | None = None
    location: str | None = None
    site_type: str | None = None
    herbicides: str | None = None
    liters_used: float | None = None
    area_ha: float | None = None
    cost_code: str | None = None
    created_at: datetime


class TimeMaterialsRowUpdate(BaseModel):
    location: str | None = None
    site_type: str | None = None
    herbicides: str | None = None
    liters_used: float | None = None
    area_ha: float | None = None
    cost_code: str | None = None


class TimeMaterialsTicketRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    ticket_number: str
    spray_date: date
    client: str
    area: str
    description_of_work: str | None = None
    po_approval_number: str | None = None
    created_by_user_id: int | None = None
    created_by_name: str | None = None
    created_at: datetime
    updated_at: datetime
    pdf_url: str | None = None
    office_data: dict | None = None  # stripped for worker role in endpoint
    approved_by_user_id: int | None = None
    approved_by_name: str | None = None
    approved_at: datetime | None = None
    approved_signature: str | None = None  # stripped for worker role in endpoint
    status: TMTicketStatus
    rows: list[TimeMaterialsRowRead] = Field(default_factory=list)


class TimeMaterialsTicketDeltaRow(BaseModel):
    """Slim view of a T&M ticket for the /delta endpoint.

    Mirrors `TimeMaterialsTicketRead` but deliberately omits the two
    heaviest fields:

      * ``office_data`` — typically a few KB of pricing JSON, but only
        consumed by the detail view (admin/office editing) and the PDF
        generator (which already re-fetches the full row before render).
      * ``approved_signature`` — base64-encoded PNG, ~30–50 KB per row.
        Only ever rendered in the detail-sheet preview and the
        signature-pad modal; the list view never reads it.

    Detail open via ``GET /api/time-materials/{ticket_id}`` still returns
    the full ``TimeMaterialsTicketRead``, so neither field is lost — they
    just don't ship on every poll-tick of every admin's FormsPanel.

    Frontend cache merge note: the FormsPanel writes delta items into
    the offline ``tmTickets`` IndexedDB store. ``upsertTMTickets`` does a
    spread-merge against any existing cache row, so a slim payload coming
    over the wire never clobbers heavy fields that were warmed by an
    earlier full-list fetch or detail open.
    """
    model_config = ConfigDict(from_attributes=True)

    id: int
    ticket_number: str
    spray_date: date
    client: str
    area: str
    description_of_work: str | None = None
    po_approval_number: str | None = None
    created_by_user_id: int | None = None
    created_by_name: str | None = None
    created_at: datetime
    updated_at: datetime
    pdf_url: str | None = None
    approved_by_user_id: int | None = None
    approved_by_name: str | None = None
    approved_at: datetime | None = None
    status: TMTicketStatus
    rows: list[TimeMaterialsRowRead] = Field(default_factory=list)


class TMTicketsDeltaResponse(BaseModel):
    """Incremental T&M tickets update — see /api/time-materials/delta.

    `items` — tickets created/updated (and still visible) since `since`.
    `ids_removed` — ticket IDs that were soft-deleted since `since`;
    frontend should drop them from its local cache.
    `server_time` — pass this back as `?since=` on the next call.
    """
    items: list[TimeMaterialsTicketDeltaRow]
    ids_removed: list[int]
    server_time: datetime


class TimeMaterialsTicketCreate(BaseModel):
    spray_date: date
    client: str
    area: str
    description_of_work: str | None = None


class TimeMaterialsTicketUpdate(BaseModel):
    description_of_work: str | None = None
    client: str | None = None
    area: str | None = None
    po_approval_number: str | None = None
    office_data: dict | None = None
    status: TMTicketStatus | None = None
    pdf_base64: str | None = None
    approved_signature: str | None = None   # base64 PNG from draw-pad
    approve: bool = False                    # set approved_by/at, status=approved
    row_updates: list[dict] | None = None    # [{ id, cost_code, ... }] batch update rows
    new_rows: list[dict] | None = None       # admin-added manual rows (no spray_record_id)
    rows_to_delete: list[int] | None = None  # ids of manual rows to remove


# ── Hydroseed schemas ────────────────────────────────────────────────────────

class HydroseedTicketRowRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: int
    ticket_id: int
    daily_record_id: int | None = None
    kind: str
    label: str
    qty: float | None = None
    unit: str | None = None
    cost_code: str | None = None
    created_at: datetime


class HydroseedLinkedDaily(BaseModel):
    """Slim summary of a daily that's linked to a hydroseed ticket. Exposed
    on `HydroseedTicketRead.linked_dailies` so the detail sheet + PDF can
    show the HD###### list without round-tripping each daily.

    Header-level fields from `daily_data` (customer rep, lead, supervisor,
    crew names, payroll hours, crew-truck/water-truck/travel scalars) are
    surfaced here too so the HT PDF generator can paper-form-render them
    without pulling the full daily snapshot. They're hoisted out of the
    JSONB blob in `_hoist_from_daily_data` below so the API payload stays
    slim (no loads array, no photos)."""
    model_config = ConfigDict(from_attributes=True)
    id: int
    record_number: str
    work_date: date
    site_name: str | None = None
    # Hoisted from daily_data
    customer_rep: str | None = None
    customer_rep_phone: str | None = None
    supervisor: str | None = None
    lead: str | None = None
    workers: list[str] = Field(default_factory=list)
    crew: list[str] = Field(default_factory=list)        # legacy fallback
    supervisor_hours: float | None = None
    lead_hours: float | None = None
    labour_hours_per_person: float | None = None
    crew_truck_count: float | None = None
    crew_truck_hours: float | None = None
    water_truck_loads: float | None = None
    travel_km: float | None = None

    @model_validator(mode="before")
    @classmethod
    def _hoist_from_daily_data(cls, v):
        # Accept both ORM objects (have `.daily_data` attr) and dicts (tests).
        # Pull the slim subset of daily_data fields we need into the top-level
        # validation payload so the resulting model carries them as proper
        # typed fields instead of a free-form `daily_data: dict`.
        if v is None:
            return v
        if isinstance(v, dict):
            payload = dict(v)
            daily_data = payload.get("daily_data") or {}
        else:
            payload = {
                "id": getattr(v, "id", None),
                "record_number": getattr(v, "record_number", None),
                "work_date": getattr(v, "work_date", None),
                "site_name": getattr(v, "site_name", None),
            }
            daily_data = getattr(v, "daily_data", None) or {}
        for key in (
            "customer_rep",
            "customer_rep_phone",
            "supervisor",
            "lead",
            "workers",
            "crew",
            "supervisor_hours",
            "lead_hours",
            "labour_hours_per_person",
            "crew_truck_count",
            "crew_truck_hours",
            "water_truck_loads",
            "travel_km",
        ):
            if key not in payload and daily_data.get(key) is not None:
                payload[key] = daily_data.get(key)
        return payload


class HydroseedTicketRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: int
    ticket_number: str
    work_date: date
    client: str
    area: str
    description_of_work: str | None = None
    po_approval_number: str | None = None
    created_by_user_id: int | None = None
    created_by_name: str | None = None
    created_at: datetime
    updated_at: datetime
    pdf_url: str | None = None
    office_data: dict | None = None       # stripped for worker role in endpoint
    approved_by_user_id: int | None = None
    approved_by_name: str | None = None
    approved_at: datetime | None = None
    approved_signature: str | None = None  # stripped for worker role in endpoint
    status: TMTicketStatus
    rows: list[HydroseedTicketRowRead] = Field(default_factory=list)
    # Slim summary of HD###### records linked to this ticket. The field
    # name matches the SQLAlchemy relationship so `from_attributes=True`
    # populates it directly without any alias gymnastics.
    daily_records: list[HydroseedLinkedDaily] = Field(default_factory=list)

    @field_validator("daily_records", mode="before")
    @classmethod
    def _exclude_soft_deleted_dailies(cls, v):
        # The SQLAlchemy relationship doesn't filter soft-deleted dailies; do
        # it here so the detail sheet + PDF never reference an HD record the
        # office has already removed. Compatible with both ORM lists and
        # pre-built dicts (e.g. in tests).
        if v is None:
            return v
        out = []
        for d in v:
            deleted_at = getattr(d, "deleted_at", None) if not isinstance(d, dict) else d.get("deleted_at")
            if deleted_at is not None:
                continue
            out.append(d)
        return out


class HydroseedTicketDeltaRow(BaseModel):
    """Slim delta-payload view. Omits office_data + approved_signature.
    Same rationale as TimeMaterialsTicketDeltaRow."""
    model_config = ConfigDict(from_attributes=True)
    id: int
    ticket_number: str
    work_date: date
    client: str
    area: str
    description_of_work: str | None = None
    po_approval_number: str | None = None
    created_by_user_id: int | None = None
    created_by_name: str | None = None
    created_at: datetime
    updated_at: datetime
    pdf_url: str | None = None
    approved_by_user_id: int | None = None
    approved_by_name: str | None = None
    approved_at: datetime | None = None
    status: TMTicketStatus
    rows: list[HydroseedTicketRowRead] = Field(default_factory=list)


class HydroseedTicketsDeltaResponse(BaseModel):
    items: list[HydroseedTicketDeltaRow]
    ids_removed: list[int]
    server_time: datetime


class HydroseedTicketCreate(BaseModel):
    work_date: date
    client: str
    area: str
    description_of_work: str | None = None


class HydroseedTicketUpdate(BaseModel):
    description_of_work: str | None = None
    client: str | None = None
    area: str | None = None
    po_approval_number: str | None = None
    office_data: dict | None = None
    status: TMTicketStatus | None = None
    pdf_base64: str | None = None
    approved_signature: str | None = None
    approve: bool = False


class HydroseedTicketLink(BaseModel):
    """Picker payload on daily submit — link to existing HT or create new."""
    ticket_id: int | None = None
    create: bool = False
    description_of_work: str | None = None


class HydroseedDailyRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: int
    record_number: str
    work_date: date
    client: str
    area: str
    site_name: str | None = None
    description_of_work: str | None = None
    mulch_type: str | None = None
    comments: str | None = None
    photo_urls: list | None = None
    seed_tag_photo_urls: list | None = None
    daily_data: dict | None = None
    pdf_url: str | None = None
    site_id: int | None = None
    hydroseed_ticket_id: int | None = None
    latitude: float | None = None
    longitude: float | None = None
    created_by_user_id: int | None = None
    created_by_name: str | None = None
    created_at: datetime
    updated_at: datetime
    client_submission_id: str | None = None


class HydroseedDailyCreate(BaseModel):
    """Submit payload for POST /api/hydroseed/dailies. The full form snapshot
    rides in `daily_data`; top-level fields denormalize for indexing."""
    work_date: date
    client: str
    area: str
    site_name: str | None = None
    description_of_work: str | None = None
    mulch_type: str | None = None
    comments: str | None = None
    daily_data: dict | None = None
    # base64 PDF rendered by frontend at submit time
    pdf_base64: str | None = None
    # Inline base64 photos (annotated maps / canvas / uploaded photos). Each is
    # { data: base64, type: 'image/jpeg' } — backend uploads to Dropbox and
    # stores the resulting URLs into `photo_urls`.
    photos: list[dict] | None = None
    # Same shape, separate bucket for seed bag tag photos.
    seed_tag_photos: list[dict] | None = None
    site_id: int | None = None
    latitude: float | None = None
    longitude: float | None = None
    client_submission_id: str | None = None
    hydroseed_ticket_link: HydroseedTicketLink | None = None


class HydroseedDailyUpdate(BaseModel):
    work_date: date | None = None
    client: str | None = None
    area: str | None = None
    site_name: str | None = None
    description_of_work: str | None = None
    mulch_type: str | None = None
    comments: str | None = None
    daily_data: dict | None = None
    pdf_base64: str | None = None
    photos: list[dict] | None = None
    seed_tag_photos: list[dict] | None = None
    hydroseed_ticket_link: HydroseedTicketLink | None = None


class HydroseedDailyDeltaResponse(BaseModel):
    items: list[HydroseedDailyRead]
    ids_removed: list[int]
    server_time: datetime
